### PR TITLE
spec: mark the ceph-iscsi-tools package deprecated

### PR DESCRIPTION
**Pull request by lxbsz**
Ceph cluster now incorporates a generic metric gathering framework
within the OSDs and MGRs to provide built-in monitoring.

Signed-off-by: Xiubo Li <xiubli@redhat.com>

### CODE REVIEW

**Comment by idryomov** [comment]
I'd update the commit message to say that otherwise an upgrade of ceph-iscsi on a system with ceph-iscsi-tools installed would fail (just to make it clear to folks who are not familiar with RPM and spec files).

**Review by idryomov — APPROVED** [review]

**Comment by lxbsz** [comment]
> I'd update the commit message to say that otherwise an upgrade of ceph-iscsi on a system with ceph-iscsi-tools installed would fail (just to make it clear to folks who are not familiar with RPM and spec files).

Sure, thanks. I will backport this later this week.

**Comment by lxbsz** [comment]
> I'd update the commit message to say that otherwise an upgrade of ceph-iscsi on a system with ceph-iscsi-tools installed would fail (just to make it clear to folks who are not familiar with RPM and spec files).

Sorry I misreaded this and triggered the merge button :-(.

**Comment by idryomov** [comment]
No problem -- I should have just left a comment instead of approving right away.

**Pull request merged**
