### PR TITLE
Target level CHAP authentication and TPG lun_id persistence

### PR DESCRIPTION
**Pull request by ricardoasmarques**
This PR contains 2 different commits to fix both topics discussed on issue https://github.com/ceph/ceph-iscsi/issues/130

**1. Target level CHAP authentication**
It's now possible to define CHAP/MUTUAL_CHAP authentication at the target level (same credentials are applied to all TPGs).
When using ACL, those credentials will be inherited and can be overridden at the client level.

**2. Persist TPG lun_id**
Instead of relying on storage object path to generate it, TPG `lun_id` will now be persisted in the `gateway.conf` ensuring that the TPG `lun_id` is the same in all gateways, and will not change across restarts.

Fixes https://github.com/ceph/ceph-iscsi/issues/130

### CODE REVIEW

**Comment by ddiss** [comment]
As discussed, I'm a little confused by the  need for inheritance of TPG level CHAP settings into the client ACLs. I'd like to understand why we can't rely on the default LIO behaviour here, so will do some further investigation.

**Comment by ricardoasmarques** [comment]
> As discussed, I'm a little confused by the need for inheritance of TPG level CHAP settings into the client ACLs. I'd like to understand why we can't rely on the default LIO behaviour here, so will do some further investigation.

Setting auth credentials at target-level and have those credentials applied to all ACL clients seemed to me like a useful behavior from the usability point of view but if we conclude that it's not a good idea I can change it.

@mikechristie do you have an opinion about this?

@ddiss thanks for looking into the default LIO behavior, let us know when you have any conclusion.

**Comment by ddiss** [comment]
> As discussed, I'm a little confused by the need for inheritance of TPG level CHAP settings into the client ACLs. I'd like to understand why we can't rely on the default LIO behaviour here, so will do some further investigation.

I had a play with this on mainline kernel and LIO behaved as expected:

- ${tpgt}/attrib/authentication=1, ${tpgt}/attrib/generate_node_acls=1, ${tpgt}/auth set and ${tpgt}/acls/${initiator}/auth set
  - initiators with explicit acls/${initiator} entries use those auth settings, initiators without explicit acls use TPG auth settings
- ${tpgt}/attrib/authentication=1, ${tpgt}/attrib/generate_node_acls=0, ${tpgt}/auth set and ${tpgt}/acls/${initiator}/auth set
  - only initiators with explicit acls can login using acl auth settings

@ricardoasmarques you mentioned that you were seeing some unexpected behaviour when not performing inheritance within ceph-iscsi. Could you elaborate a bit? It'd be good if you could also share your configfs settings for this case.

**Comment by ricardoasmarques** [comment]
@ddiss Note that your first example is not valid when using `ceph-iscsi` because `generate_node_acls` is automatically set to `0` when you add an ACL/initiator from `ceph-iscsi` (and you cannot set it back to `1` unless you remove all ACLs/initiators).

The scenario I was trying to configure using `ceph-iscsi` was:
- set target-level chap auth
- add an initiator to the target
- _(I was surprised that the initiator is not able to connect using credentials defined at the target level, thats why I've implemented the "inheritence")_

This is the LIO configuration before I've implemented the "inheritence":

- ${tpgt}/attrib/authentication=1
- ${tpgt}/attrib/generate_node_acls=0
- ${tpgt}/auth set
- ${tpgt}/acls/${initiator}/auth **NOT** set
- _(initiator **cannot** connect using `${tpgt}/auth` credentials)_

With the "inheritence" that I've implemented LIO will be:

- ${tpgt}/attrib/authentication=1
- ${tpgt}/attrib/generate_node_acls=0
- ${tpgt}/auth set
- ${tpgt}/acls/${initiator}/auth set (with credentials from ${tpgt}/auth)
- _(initiator **can** connect using `${tpgt}/auth` credentials)_

**Comment by ddiss** [comment]
> @ddiss Note that your first example is not valid when using `ceph-iscsi` because `generate_node_acls` is automatically set to `0` when you add an ACL/initiator from `ceph-iscsi` (and you cannot set it back to `1` unless you remove all ACLs/initiators).

Okay, I guess that makes sense.

> 
> The scenario I was trying to configure using `ceph-iscsi` was:
> 
>     * set target-level chap auth
> 
>     * add an initiator to the target
> 
>     * _(I was surprised that the initiator is not able to connect using credentials defined at the target level, thats why I've implemented the "inheritence")_
> 
> 
> This is the LIO configuration before I've implemented the "inheritence":
> 
>     * ${tpgt}/attrib/authentication=1
> 
>     * ${tpgt}/attrib/generate_node_acls=0
> 
>     * ${tpgt}/auth set
> 
>     * ${tpgt}/acls/${initiator}/auth **NOT** set
> 
>     * _(initiator **cannot** connect using `${tpgt}/auth` credentials)_

With  ${tpgt}/attrib/authentication=1 configured, LIO doesn't do any fallback from ${tpgt}/acls/${initiator}/auth to the TPG auth settings. acls must be configured with auth settings.
I wasn't aware that ceph-iscsi allowed for "client" configurations to be present without auth settings.


> With the "inheritence" that I've implemented LIO will be:
> 
>     * ${tpgt}/attrib/authentication=1
> 
>     * ${tpgt}/attrib/generate_node_acls=0
> 
>     * ${tpgt}/auth set
> 
>     * ${tpgt}/acls/${initiator}/auth set (with credentials from ${tpgt}/auth)
> 
>     * _(initiator **can** connect using `${tpgt}/auth` credentials)_

If a "client" configuration is present with explicit auth settings will the TPG auth settings be ignored or inherited (overwriting the explicit settings)?

**Comment by ricardoasmarques** [comment]
> With ${tpgt}/attrib/authentication=1 configured, LIO doesn't do any fallback from ${tpgt}/acls/${initiator}/auth to the TPG auth settings. acls must be configured with auth settings.
> I wasn't aware that ceph-iscsi allowed for "client" configurations to be present without auth settings.

@ddiss  Yes, `ceph-iscsi` allows using ACL without auth credentials.

> If a "client" configuration is present with explicit auth settings will the TPG auth settings be ignored or inherited (overwriting the explicit settings)?

@ddiss Explicit "client-level" auth will override the "target-level" auth, for example, doing the following in `ceph-iscsi`:

- set target-level auth (**user1/pass1**)
- add initiator-1
- add initiator-2
- set client-level auth for initiator-1 (**user2/pass2**)

Will result in the following LIO configuration:

- ${tpgt}/attrib/authentication=1
- ${tpgt}/attrib/generate_node_acls=0
- ${tpgt}/auth set to **user1/pass1**
- ${tpgt}/acls/${initiator-1}/auth set to **user2/pass2**
- ${tpgt}/acls/${initiator-2}/auth set to **user1/pass1**

**Comment by ddiss** [comment]
> > If a "client" configuration is present with explicit auth settings will the TPG auth settings be ignored or inherited (overwriting the explicit settings)?
> 
> @ddiss Explicit "client-level" auth will override the "target-level" auth, for example, doing the following in `ceph-iscsi`:
> 
>     * set target-level auth (**user1/pass1**)
> 
>     * add initiator-1
> 
>     * add initiator-2
> 
>     * set client-level auth for initiator-1 (**user2/pass2**)
> 
> 
> Will result in the following LIO configuration:
> 
>     * ${tpgt}/attrib/authentication=1
> 
>     * ${tpgt}/attrib/generate_node_acls=0
> 
>     * ${tpgt}/auth set to **user1/pass1**
> 
>     * ${tpgt}/acls/${initiator-1}/auth set to **user2/pass2**
> 
>     * ${tpgt}/acls/${initiator-2}/auth set to **user1/pass1**

Thanks for the explanation. If the target-level auth is removed after this point, does initiator-2 retain the inherited username / password? Given that ACL auth is either enabled or disabled for all initiators, I can't see what else would make sense here.

I'd be interested to hear @mikechristie 's thoughts on whether the ACL->TPG auth fallback should be handled in kernel.

**Comment by mikechristie** [comment]
Give me a day to think about it some more.

Just some background, because I want to make sure we are not carrying over some funky behavior due to my misunderstanding of how LIO works.

My understanding was that you cannot have a TPG with 2 ACLs where one uses CHAP and one uses initiator name based auth. There is a funky way to almost enable it by setting the AuthMethod directly, but it results in some buggy cases.

So with that assumption, we had allowed you to create ACLs with CHAP and without but it currently can leave the system in a weird state where some work and some do not and we just document the user has to pick one (gwcli lists the auth state as misconfigured). This is basically just to let the user switch between CHAP and initiator name based ACLs or the reverse while they set up.

My goal was to fix up the kernel so it allowed this type of mixing and what I think you describe as auth fallback. Give me a couple days to try and recover it. I think I hit several issues and just didn't have time to complete it and my workstation died first :) but I have the drive still.

**Comment by ricardoasmarques** [comment]
> > > If a "client" configuration is present with explicit auth settings will the TPG auth settings be ignored or inherited (overwriting the explicit settings)?
> > 
> > 
> > @ddiss Explicit "client-level" auth will override the "target-level" auth, for example, doing the following in `ceph-iscsi`:
> > ```
> > * set target-level auth (**user1/pass1**)
> > 
> > * add initiator-1
> > 
> > * add initiator-2
> > 
> > * set client-level auth for initiator-1 (**user2/pass2**)
> > ```
> > 
> > 
> > Will result in the following LIO configuration:
> > ```
> > * ${tpgt}/attrib/authentication=1
> > 
> > * ${tpgt}/attrib/generate_node_acls=0
> > 
> > * ${tpgt}/auth set to **user1/pass1**
> > 
> > * ${tpgt}/acls/${initiator-1}/auth set to **user2/pass2**
> > 
> > * ${tpgt}/acls/${initiator-2}/auth set to **user1/pass1**
> > ```
> 
> Thanks for the explanation. If the target-level auth is removed after this point, does initiator-2 retain the inherited username / password? Given that ACL auth is either enabled or disabled for all initiators, I can't see what else would make sense here.

In the current implementation of this PR, you will end up with the following LIO implementation:

* ${tpgt}/attrib/authentication=1

* ${tpgt}/attrib/generate_node_acls=0

* ${tpgt}/auth **NOT** set
 
* ${tpgt}/acls/${initiator-1}/auth set to **user2/pass2**

* ${tpgt}/acls/${initiator-2}/auth **NOT** set

As @mikechristie said, this will be considered a "misconfigured" and "initiator-2" will not be able to connect until auth is set for "initiator-2" or auth is removed from "initiator-1".

**Comment by mikechristie** [comment]
I can't find my old patches, but I think we need a new setting on the ACL that indicates if we do:

1. CHAP using the ACL values.
2. Initiator name based ACL (just match initiator name on the ACL).
3. Fall back to the TPG level authentication values.

In iscsi_target_handle_csg_zero we would then check this new setting instead of only going by the tpg authentication setting.

**Comment by ddiss** [comment]
> I can't find my old patches, but I think we need a new setting on the ACL that indicates if we do:
> 
>     CHAP using the ACL values.
>     Initiator name based ACL (just match initiator name on the ACL).
>     Fall back to the TPG level authentication values.
> 
> In iscsi_target_handle_csg_zero we would then check this new setting instead of only going by the tpg authentication setting.

Sounds reasonable to me. I'll put something together to do this.

**Comment by ricardoasmarques** [comment]
@ddiss @mikechristie Any chance we can review/merge this PR before implementing the kernel changes, or do we have to block it until then?

Maybe we can use the "manual fallback to target auth" implemented in this PR for now, and adapt it later when kernel supports the fallback at LIO level. Or we can remove the "auth fallback" from this PR. Thoughts?

**Comment by mikechristie** [comment]
The lun_id patch should definitely go in before the auth stuff since it's not related and I think it fixes a bug.

For the CHAP part, I am ok with any option as long as we can do it in a way that does not break setups in the future or we should at least have a upgrade path.

For the CHAP behavior, I am ok with the behavior implemented in your patch. If we want to discuss it some more and/or make sure we can make the kernel interface do what we want because that code can get quirky, I would suggest to break it up into 2 PRs so the lun_id stuff go in first.

**Comment by ricardoasmarques** [comment]
@mikechristie to avoid having to wait for kernel changes, and to avoid having to remove the code that implements the "auth fallback" in `ceph-iscsi` later, I've updated this PR with a different approach.

With my latest changes `ceph-iscsi` will **NOT** allow mixing TPG/target auth with ACL auth.

This means that:
- if TPG/target auth is being used, then the user is not allowed to enable ACL / add clients
- if ACL auth is enabled, then the user is not able to set TPG/target auth

If in the future we really have the need of mixing both, then we can follow up the `kernel`+`ceph-iscsi` discussion later, and have a dedicated PR just for that.

@mikechristie @ddiss if you agree with this "simpler" approach, then this PR is now ready for review. Thanks.

**Comment by mikechristie** [comment]
That seems ok to me.

**Comment by mikechristie** [comment]
@ddiss 

I didn't see any objections from you and see you built some other patches on @ricardoasmarques's set here, so I am going to merge it up.

Feel free to just send a PR for whatever changes you want in the future.

**Comment by mikechristie** [comment]
Just adding a note.

This exposes an issue where one node will upgrade to 9.5 only but the code now assumes 11, so if the other nodes do not upgrade fast enough, you will hit a crash when trying to access the new config object fields during initialization. That will be fixed in a updated

https://github.com/ceph/ceph-iscsi/pull/144

which will fix the loop issue and this one.

**Pull request merged**
